/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LEDpin1.c
**     Project     : ProcessorExpert
**     Processor   : MKL25Z128VLK4
**     Component   : GenericBitIO
**     Version     : Component 01.065, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2014-02-24, 11:50, # CodeGen: 1
**     Abstract    :
**
**     Settings    :
**
**     Contents    :
**         GetDir - bool LEDpin1_GetDir(void);
**         GetVal - bool LEDpin1_GetVal(void);
**         PutVal - void LEDpin1_PutVal(bool Val);
**         ClrVal - void LEDpin1_ClrVal(void);
**         SetVal - void LEDpin1_SetVal(void);
**         NegVal - void LEDpin1_NegVal(void);
**         Init   - void LEDpin1_Init(void);
**
**     License : Open Source (LGPL)
**     Copyright : (c) Copyright Erich Styger, 2011, all rights reserved.
**     This an open source software implementing a generic Bit I/O driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LEDpin1.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup LEDpin1_module LEDpin1 module documentation
**  @{
*/         

/* MODULE LEDpin1. */

#include "LEDpin1.h"

/*
** ===================================================================
**     Method      :  LEDpin1_GetDir (component GenericBitIO)
**     Description :
**         Return the direction of the pin (input/output)
**     Parameters  : None
**     Returns     :
**         ---             - FALSE if port is input, TRUE if port is
**                           output
** ===================================================================
*/
/* This method is implemented as macro in header file LEDpin1.h
bool LEDpin1_GetDir(void)
{
}
*/
/*
** ===================================================================
**     Method      :  LEDpin1_GetVal (component GenericBitIO)
**     Description :
**         Returns the pin value
**     Parameters  : None
**     Returns     :
**         ---             - Returns the value of the pin:
**                           FALSE/logical level '0' or TRUE/logical
**                           level '1'
** ===================================================================
*/
/* This method is implemented as macro in header file LEDpin1.h
bool LEDpin1_GetVal(void)
{
}
*/

/*
** ===================================================================
**     Method      :  LEDpin1_PutVal (component GenericBitIO)
**     Description :
**         Sets the pin value
**     Parameters  :
**         NAME            - DESCRIPTION
**         Val             - Value to set. FALSE/logical '0' or
**                           TRUE/logical '1'
**     Returns     : Nothing
** ===================================================================
*/
/* This method is implemented as macro in header file LEDpin1.h
void LEDpin1_PutVal(bool Val)
{
}
*/

/*
** ===================================================================
**     Method      :  LEDpin1_ClrVal (component GenericBitIO)
**     Description :
**         Clears the pin value (sets it to a low level)
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/* This method is implemented as macro in header file LEDpin1.h
void LEDpin1_ClrVal(void)
{
}
*/

/*
** ===================================================================
**     Method      :  LEDpin1_SetVal (component GenericBitIO)
**     Description :
**         Sets the pin value to a high value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/* This method is implemented as macro in header file LEDpin1.h
void LEDpin1_SetVal(void)
{
}
*/

/*
** ===================================================================
**     Method      :  LEDpin1_NegVal (component GenericBitIO)
**     Description :
**         Toggles/negates the pin value
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/* This method is implemented as macro in header file LEDpin1.h
void LEDpin1_NegVal(void)
{
}
*/

/*
** ===================================================================
**     Method      :  LEDpin1_Init (component GenericBitIO)
**     Description :
**         Initializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LEDpin1_Init(void)
{
   LEDpin1_ClrVal(); /* clear bit to set data to 0 */
   PTADD_PTADD0 = 1; /* set bit for output mode */
}

/* END LEDpin1. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.08]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
